### ISSUE TITLE
can't access assembly from ftp site

### ISSUE THREAD

**Issue by droeatumn** [PuertoRicanGenome/Assembly#1]
I can't get to the ftp locate for the assembly. 

When I run 'wget ftp://ftp.ccb.jhu.edu/pub/data/Homo_sapiens/PR1/v1.0/Assembly/PR1.fa.gz', I get
couldn't connect to 128.220.174.63 port 8032: Connection timed out

Here is the output from ftp:
Connected to salz-ftp.idies.jhu.edu.
220 (vsFTPd 3.0.2)
Name (ftp.ccb.jhu.edu:roex0050): anonymous
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> quote pasv
227 Entering Passive Mode (128,220,174,63,31,100).
ftp> ls
200 PORT command successful. Consider using PASV.
425 Failed to establish connection.

**Comment by PuertoRicanGenome** [comment]
Hello,

This might be due to a slow Internet/ftp server connection.   I've just tried and everything worked fine for me. 
Could you try again?

$ wget  ftp://ftp.ccb.jhu.edu/pub/data/Homo_sapiens/PR1/v1.0/Assembly/PR1.fa.gz
--2021-06-15 12:10:29--  ftp://ftp.ccb.jhu.edu/pub/data/Homo_sapiens/PR1/v1.0/Assembly/PR1.fa.gz
           => ‘PR1.fa.gz’
Resolving ftp.ccb.jhu.edu (ftp.ccb.jhu.edu)... 128.220.174.63
Connecting to ftp.ccb.jhu.edu (ftp.ccb.jhu.edu)|128.220.174.63|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/data/Homo_sapiens/PR1/v1.0/Assembly ... done.
==> SIZE PR1.fa.gz ... 897200065
==> PASV ... done.    ==> RETR PR1.fa.gz ... done.
Length: 897200065 (856M) (unauthoritative)

PR1.fa.gz                                          100%[===============================================================================================================>] 855.64M  20.4MB/s    in 76s

2021-06-15 12:11:46 (11.2 MB/s) - ‘PR1.fa.gz’ saved [897200065]

$ ftp ftp.ccb.jhu.edu
Connected to salz-ftp.idies.jhu.edu.
220 (vsFTPd 3.0.2)
Name (ftp.ccb.jhu.edu:dpuiu): anonymous
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
-rw-------    1 0        5042            0 Feb 28  2013 dsmerlog.pru
-rw-------    1 0        5042          126 Feb 28  2013 dsmerror.log
drwxrwsr-x   18 2612     5042           18 Feb 22 15:43 incoming
drwxrwsr-x   28 2612     5042           28 Mar 19  2020 pub
226 Directory send OK.
ftp> cd pub/data/Homo_sapiens/PR1/v1.0/Assembly
250 Directory successfully changed.
ftp> ls
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
-rw-rw-r--    1 2667     5042         3241 Jun 07 21:33 PR1.fa.fai
-rw-rw-r--    1 2667     5042     897200065 Jun 07 21:30 PR1.fa.gz
-rw-rw-r--    1 2667     5042           44 Jun 08 09:34 md5sum.txt
226 Directory send OK.
ftp> get PR1.fa.gz
local: PR1.fa.gz remote: PR1.fa.gz
200 PORT command successful. Consider using PASV.
150 Opening BINARY mode data connection for PR1.fa.gz (897200065 bytes).

**Comment by droeatumn** [comment]
I confirm the problem appears to be on my side. My apologies.
